#!/bin/bash

# Author = "Abhijit Maity & Dhirendra Deora"
# Last Update Date = "15-Jul-2015"


echo "Enter File Name :"
read file
echo "Enter Legitimate IP's Source Organisation Name :"
read name
echo
echo "Please wait.."
echo

c=`wc -l $file | cut -d " " -f1`
count=0
f=0
t=1

for (( i=1 ; i <= $c ; i++ ))
do
	ip=`sed -n ''$i'p' $file`
	search=`whois $ip | grep -i $name | wc -l`
	if [ "$search" != 0 ]
	then
		f=1
		echo
		count=`expr "$count" + "$t"`
                echo
                echo $count "IP found !!!"
		echo
		echo $ip >> who_is_output_$file_$name.txt 
	fi
	stat=`expr "$c" - "$i"`
	echo $stat "IPs are left..."
done

if [ "$f" == 0  ]
then
	echo "Sorry !! No IPs were found !!!"
else
	echo	
	echo "Thats it !!! We are done..."
	echo $count "IPs were found !!! Please check the output file 'who_is_output_$name.txt'..."
	echo
fi
